Retention time correction and additional peak fitting algorithm (#21)
* bump to 1.3.0 devel version

* Bump to 1.3.0 devel version

* Ransac algorithm (#20)

* rtCorrection_utils.R, add back placeholder for retention time correction

* rt_correction interface work

* update to R4.0, minor style corrections

* # inst: scripts/make_unittest_data.R added
Sync branch with develop

* rtCorrection_utils:
- Rt correction polynomial model added
- RANSAC algorithm added
methods_peakPantheRAnnotation.R:
- Rt correction method modified

* methods_peakPantheRAnnotation.R:
- Rt correction method modified
- diagnostic plot added

* methods_peakPantheRAnnotation.R:
- small changes
- applyRTCorrection unitests

* methods_peakPantheRAnnotation.R:
- Change to figure axes label
tests:
- test_peakPantheRAnnotation_retentionTimeCorrection-method.R added - tests for peakPantheRAnnotation object method and plot

* methods_peakPantheRAnnotation.R:
- Documentation fix

* parallel-annotation.Rmd:
- add retention time correction example

* BioC style corrections (T/F, stats::)

* fix travis allowed failures

* updated vignettes

* documentation correction `retentionTimeCorrection` method

* sort line > 80 character in code

* sort line > 80 character in man and vignette

* fix indent to multiples of 4

* fix function length:
add ggplot variables from rtCorrection diag plot to globalVars

* fix function length (in progress):
modifications in method and related unittests and correction utils

* fix function length (in progress):
modifications to RANSAC

* documentation change
* RtCorrection_method - fix defaults and parameters in method definition

Co-authored-by: Arnaud M. Wolfer <adwolfer@gmail.com>

* updated NEWS

* Feature/emg gaussian (#22)

* curveFit_utils.Rmd:
- added cerf function and equations for emgGaussian
* findTargetFeatures, peakPantheR_parallelAnnotation and peakPantheR_singleFileSearch.R:
- curveModel arguments to support emgGaussian
* add new .rD man files
add osx fortran clause to travis
* move to travis.com in README
* - Modifications to parallel and singleFilesearch for new model
Added unittests for emgGaussian lineshape
* - fitCurve test_added
* New travis setup: release allowed to fail and biocCheck does not check version number in release
* add predictCurve test with emgGaussian
* travis modification to terminate OSX builds
* travis no codecov on OSX
* added mention of curveModel to vignette docs and function calls

Co-authored-by: Arnaud M. Wolfer <adwolfer@gmail.com>

* increased codecov coverage

* curveModel test coverage

* travis BiocStyle

* add Suggest to travis

* increased codecov coverage

Co-authored-by: gscorreia89 <gscorreia89@gmail.com>

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,24 +1,86 @@
 language: r
 cache: packages
 
-os:
-  - linux
-  - osx
 
-r:
-  - bioc-devel
-  - bioc-release
-
-matrix:
+jobs:
+  include:
+  - r: bioc-devel
+    os: linux
+  - r: bioc-devel
+    os: osx
+    before_install:
+      - brew update
+      - rm '/usr/local/bin/gfortran'
+      - brew install libgit2
+  - r: bioc-release
+    os: linux
+    before_install:
+      - cat DESCRIPTION
+      - export PACKAGE_NAME='peakPantheR'
+      - export RCHECK_DIR=${PACKAGE_NAME}.Rcheck
+      - echo ${RCHECK_DIR}
+    script:
+      - R CMD build .
+      - PKG_TARBALL=$(ls -1t *.tar.gz | head -n 1)
+      - R CMD check ${PKG_TARBALL} --as-cran; CHECK_RET=$? ;
+      - Rscript -e "library(BiocCheck); BiocCheck(\"${PKG_TARBALL}\", 'no-check-version-num'=TRUE)"
+      - Rscript -e "message(devtools::check_failures(path = \"${RCHECK_DIR}\"))"
+      - if [[ $CHECK_RET -ne 0 ]];
+        then
+          echo "R CMD check failed";
+          travis_terminate 1;
+        fi
+      - grep -q -R "WARNING" "${RCHECK_DIR}/00check.log";
+        if [[ $? -eq 0 ]];
+        then
+          echo "Found warnings, treating as errors (as requested).";
+          exit 1;
+        fi
+  - r: bioc-release
+    os: osx
+    before_install:
+      - brew update
+      - rm '/usr/local/bin/gfortran'
+      - brew install libgit2
+      - cat DESCRIPTION
+      - export PACKAGE_NAME='peakPantheR'
+      - export RCHECK_DIR=${PACKAGE_NAME}.Rcheck
+      - echo ${RCHECK_DIR}
+    script:
+      - R CMD build .
+      - PKG_TARBALL=$(ls -1t *.tar.gz | head -n 1)
+      - R CMD check ${PKG_TARBALL} --as-cran; CHECK_RET=$? ;
+      - Rscript -e "library(BiocCheck); BiocCheck(\"${PKG_TARBALL}\", 'no-check-version-num'=TRUE)"
+      - Rscript -e "message(devtools::check_failures(path = \"${RCHECK_DIR}\"))"
+      - if [[ $CHECK_RET -ne 0 ]];
+        then
+          echo "R CMD check failed";
+          travis_terminate 1;
+        fi
+      - grep -q -R "WARNING" "${RCHECK_DIR}/00check.log";
+        if [[ $? -eq 0 ]];
+        then
+          echo "Found warnings, treating as errors (as requested).";
+          exit 1;
+        fi
   allow_failures:
     - r: bioc-release
 
+
 bioc_required: true
 bioc_check: true
+warnings_are_errors: true
 
 r_packages:
+  - devtools
   - covr
   - faahKO
+  - testthat
+  - msdata
+  - knitr
+  - rmarkdown
+  - pander
+  - BiocStyle
 
 addons:
   apt:
@@ -27,9 +89,6 @@ addons:
       - netcdf-bin
       - libhdf5-dev
 
-before_install:
-  - "if [ ${TRAVIS_OS_NAME} = 'osx' ]; then brew update; fi"
-  - "if [ ${TRAVIS_OS_NAME} = 'osx' ]; then brew install libgit2; fi"
-
 after_success:
-  - Rscript -e 'library(covr); codecov(line_exclusions = "R/zzz.R")'
+  - "if [ ${TRAVIS_OS_NAME} != 'osx' ]; then Rscript -e 'library(covr); codecov(line_exclusions = list(\"R/zzz.R\", \"R/peakPantheR_start_GUI.R\"))'; fi"
+  - echo 'Done !'
