travis with error

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,5 +1,6 @@
 language: r
 cache: packages
+warnings_are_errors: true
 
 
 jobs:
@@ -17,8 +18,17 @@ jobs:
     script:
       - R CMD build .
       - PKG_TARBALL=$(ls -1t *.tar.gz | head -n 1)
-      - R CMD check ${PKG_TARBALL} --as-cran
-      - Rscript -e "library(BiocCheck); BiocCheck(\"${PKG_TARBALL}\")"
+      - R CMD check ${PKG_TARBALL} --as-cran; CHECK_RET=$? ;
+      - export_rcheck_dir
+      - Rscript -e "library(BiocCheck); BiocCheck(\"${PKG_TARBALL}\", 'no-check-version-num'=TRUE)"
+      - Rscript -e "message(devtools::check_failures(path = \"${RCHECK_DIR}\"))"
+      - if [[ $CHECK_RET -ne 0 ]];
+        then
+          echo "R CMD check failed";
+          check_fail;
+          dump_logs;
+          travis_terminate 1;
+        fi
   - r: bioc-release
     os: osx
     before_install:
@@ -28,8 +38,17 @@ jobs:
     script:
       - R CMD build .
       - PKG_TARBALL=$(ls -1t *.tar.gz | head -n 1)
-      - R CMD check ${PKG_TARBALL} --as-cran
+      - R CMD check ${PKG_TARBALL} --as-cran; CHECK_RET=$? ;
+      - export_rcheck_dir
       - Rscript -e "library(BiocCheck); BiocCheck(\"${PKG_TARBALL}\", 'no-check-version-num'=TRUE)"
+      - Rscript -e "message(devtools::check_failures(path = \"${RCHECK_DIR}\"))"
+      - if [[ $CHECK_RET -ne 0 ]];
+        then
+          echo "R CMD check failed";
+          check_fail;
+          dump_logs;
+          travis_terminate 1;
+        fi
   allow_failures:
     - r: bioc-release
 
