travis test warning

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -16,7 +16,7 @@ jobs:
     os: linux
     before_install:
       - cat DESCRIPTION
-      - export PACKAGE_NAME=`package_name`
+      - export PACKAGE_NAME=`peakPantheR`
       - echo ${PACKAGE_NAME};
       - export RCHECK_DIR=${PACKAGE_NAME}.Rcheck
     script:
@@ -43,7 +43,7 @@ jobs:
       - rm '/usr/local/bin/gfortran'
       - brew install libgit2
       - cat DESCRIPTION
-      - export PACKAGE_NAME=`package_name`
+      - export PACKAGE_NAME=`peakPantheR`
       - echo ${PACKAGE_NAME};
       - export RCHECK_DIR=${PACKAGE_NAME}.Rcheck
     script:
@@ -54,14 +54,14 @@ jobs:
       - Rscript -e "message(devtools::check_failures(path = \"${RCHECK_DIR}\"))"
       - if [[ $CHECK_RET -ne 0 ]];
         then
-        echo "R CMD check failed";
-        travis_terminate 1;
+          echo "R CMD check failed";
+          travis_terminate 1;
         fi
       - grep -q -R "WARNING" "${RCHECK_DIR}/00check.log";
         if [[ $? -eq 0 ]];
         then
-        echo "Found warnings, treating as errors (as requested).";
-        exit 1;
+          echo "Found warnings, treating as errors (as requested).";
+          exit 1;
         fi
   allow_failures:
     - r: bioc-release
